version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: cryptonexus-backend-1
    ports:
      - "8080"
    networks:
      - web

  frontend:
    build:
      context: ./frontend
    container_name: cryptonexus-frontend-1
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

networks:
  web:
    external: true
